# Generated by Django 3.2.4 on 2021-06-05 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Изображение')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('deleted_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
